spring:
  application:
    name: student-detail-service-dev
  profiles:
    active: dev  
  data:
    cassandra:
      contact-points:
      - 192.168.99.100
      keyspace-name: student_keyspace_dev
      port: 9042
server:
  servlet:
    context-path: /v1
  port: 8080
 