spring:
  application:
    name: zuul-api-gateway
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
server:
  port: 8762
zuul:
  prefix: /zuul
  routes:
    student-client:
      path: /v1/client/**
      serviceId: student-client
