spring:
  application:
    name: zuul-api-gateway
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
server:
  port: 8762
zuul:
  routes:
    student:
      path: /student/**
      serviceId: student-client
