spring:
  application:
    name: student-detail-service
  profiles:
    active: local  
  data:
    cassandra:
      contact-points: 127.0.0.1
      keyspace-name: student_keyspace
      port: 9042
  security:
    basic:
      enabled: false
    oauth2:
      enabled: true
      client:
        client-id: studentProtectedResourceClientIdPassword
        client-secret: secret
        check-token-endpoint-url: http://localhost:9090/spring-security-oauth-server/oauth/check_token
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/         
server:
  servlet:
    context-path: /v1
 