spring:
  application:
    name: student-detail-service-local
  profiles:
    active: local  
  data:
    cassandra:
      contact-points: 192.168.99.100
      keyspace-name: student_keyspace
      port: 9042
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/         
server:
  servlet:
    context-path: /v1
 