spring:
  application:
    name: student-detail-service-dev
  profiles:
    active: dev  
  data:
    cassandra:
      contact-points: 127.0.0.1
      keyspace-name: student_keyspace_dev
      port: 9042
server:
  servlet:
    context-path: /v1
 