spring:
  application:
    name: student-client-local
  profiles:
    active: local  
  data:
    cassandra:
      contact-points: 192.168.99.100
      keyspace-name: student_keyspace
      port: 9042